config/routes.rb
Rails.application.routes.draw do
  resources :states, only: [] do
    resources :municipalities, only: %i[index show]
  end

  resources :sessions, only: %i[new create]

  root "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mass.rb
class Mass < ApplicationRecord
  belongs_to :parish
  has_one :municipality, through: :parish

  enum day: {sunday: 0, monday: 1, tuesday: 2,
             wednesday: 3, thursday: 4, friday: 5, saturday: 6}
  enum kind: {charismatic: 0, daily: 1, dominical: 2,
              kid_friendly: 3, young_adult: 4, in_latin: 5}

  scope :for_day, ->(day) do
    where(day: day)
  end

  def parsed_time
    @parsed_time ||= begin
      time_regex = /(\d{2}):(\d{2}) (\w{2})/
      hour, minute, period = time.match(time_regex).captures
      hour, minute = [hour, minute].map(&:to_i)

      hour += 12 if period == "PM" && hour != 12

      {hour:, minute:}
    end
  end

  def happened_today?
    now = Time.current.in_time_zone(municipality.timezone)
    return false unless now.wday == day_before_type_cast
    now.change(hour: parsed_time[:hour], min: parsed_time[:minute]).before?(now)
  end
end

app/models/municipality.rb
# frozen_string_literal: true

class Municipality < ApplicationRecord
  belongs_to :state

  has_many :parishes

  def timezone
    path = Rails.root.join(TIMEZONES_FILE_PATH)
    file = File.read(path)
    yaml = Psych.safe_load(file)

    yaml["municipalities"][name.parameterize.underscore] ||
      yaml["states"][state.name.parameterize.underscore]
  end

  private

  TIMEZONES_FILE_PATH = "config/timezones.yml"
end

app/models/parish.rb
class Parish < ApplicationRecord
  belongs_to :municipality

  has_many :masses
end

app/models/state.rb
class State < ApplicationRecord
  has_many :municipalities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  def index
    @target_id = params[:target_id]
    @state = State.find(params[:state_id])
    @municipalities = @state.municipalities
  end

  def show
    @state = State.find(params[:state_id])
    @municipality = @state.municipalities.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:municipality_id] = nil if params[:reset].present?
    municipality_id = session[:municipality_id]

    if municipality_id.present?
      municipality = Municipality.find(municipality_id)
      state = municipality.state
      redirect_to state_municipality_path(state, municipality_id)
    else
      @states = State.all
    end
  end

  def create
    state = params[:state]
    municipality = params[:municipality]
    session[:municipality_id] = municipality
    redirect_to state_municipality_path(state, municipality)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisaYa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= tag.style(".translation_missing { outline: 1px solid red; }") if Rails.env.development? %>
  </head>

  <body>
    <main class="mt-28 container flex px-5 mx-auto mb-10">
      <%= yield %>
    </main>
  </body>
</html>

app/views/masses/_mass.html.erb
<%= tag.div class: ["flex flex-col items-center px-3 py-0.5 rounded-lg text-sm whitespace-nowrap",
                    {"bg-gray-100 text-gray-400": mass.happened_today?},
                    {"bg-green-100 text-green-800": !mass.happened_today?}] do %>
  <p class="font-medium"><%= mass.time %></p>
  <p><%= t("mass_kind.#{mass.kind}") %></p>
<% end %>

app/views/municipalities/index.turbo_stream.erb
<%= turbo_stream.replace @target_id do %>
  <%= select_tag "municipality",
        options_from_collection_for_select(@municipalities, :id, :name),
        include_blank: "Selecciona municipio",
        class: "form-input text-gray-700 w-full",
        data: {dynamic_select_target: "select"} %>
<% end %>

app/views/municipalities/show.html.erb
<div class="flex flex-col items-center justify-center w-full">
  <div class="bg-gray-50 rounded-3xl flex flex-col w-full max-w-lg px-6 py-3 mb-10 border border-gray-100">
    <h1 class="bold gap-y-1 flex flex-col">
      Mostrando misas en
      <span class="font-bold"><%= @municipality.name %>, <%= @municipality.state.name %></span>
    </h1>
    <%= link_to "Cambiar", new_session_path(reset: true), class: "btn btn-secondary mt-2 w-fit self-end" %>
  </div>

  <div class="gap-y-10 flex flex-col">
    <%= render @municipality.parishes %>
  </div>
</div>

app/views/parishes/_parish.html.erb
<% masses_for_today = parish.masses.for_day(Time.current.wday) %>

<div class="gap-y-4 rounded-3xl flex flex-col max-w-lg px-6 py-3 border border-gray-100">
  <h3 class="text-lg font-bold"><%= parish.name.downcase.titleize %></h3>
  <div class="gap-x-4 flex">
    <div class="gap-y-8 flex flex-col">
      <div class="space-y-2">
        <% if masses_for_today.present? %>
          <h4 class="font-bold">Misas de hoy</h4>
          <div class="grid grid-cols-3 gap-2">
            <%= render masses_for_today %>
          </div>
        <% else %>
          <p class="italic text-gray-500">No tenemos misas registradas para el día de hoy.</p>
        <% end %>
      </div>

      <div class="gap-y-2 flex flex-col">
        <h4 class="font-bold">Dirección</h4>
        <p><%= parish.address %></p>
      </div>

      <%= link_to "Ver en mapa",
            "https://maps.google.com/?q=#{parish.name}+#{parish.address}",
            class: "w-fit self-end btn btn-secondary",
            target: :_blank,
            rel: "noopener noreferrer" %>
    </div>
  </div>
</div>